version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5080:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  add-service:
    build: ./add-service/  # path is relative to docker-compose.yml location
    hostname: add-service
    ports:
      - 5051:5050  # host:container
    networks:
      sample:
        aliases:
          - add-service
  # Add more services below
  sub-service:
    build: ./sub-service  # path is relative to docker-compose.yml location
    hostname: sub-service
    ports:
      - 5052:5050  # host:container
    networks:
      sample:
        aliases:
          - sub-service
  # Add more services below
  mul-service:
    build: ./mul-service # path is relative to docker-compose.yml location
    hostname: mul-service
    ports:
      - 5053:5050  # host:container
    networks:
      sample:
        aliases:
          - mul-service
  # Add more services below
  div-service:
    build: ./div-service  # path is relative to docker-compose.yml location
    hostname: div-service
    ports:
      - 5054:5050  # host:container
    networks:
      sample:
        aliases:
          - div-service
  mod-service:
    build: ./mod-service  # path is relative to docker-compose.yml location
    hostname: mod-service
    ports:
      - 5055:5050  # host:container
    networks:
      sample:
        aliases:
          - mod-service
  exp-service:
    build: ./exp-service  # path is relative to docker-compose.yml location
    hostname: exp-service
    ports:
      - 5056:5050  # host:container
    networks:
      sample:
        aliases:
          - exp-service
  gcd-service:
    build: ./gcd-service  # path is relative to docker-compose.yml location
    hostname: gcd-service
    ports:
      - 5057:5050  # host:container
    networks:
      sample:
        aliases:
          - gcd-service
networks:
  sample: