version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
  add-service:
    build: ./add-service/  # path is relative to docker-compose.yml location
    hostname: add-service
    ports:
      - 5051:5051  # host:container
    networks:
      sample:
        aliases:
          - add-service
  # Add more services below
  sub-service:
    build: ./sub-service  # path is relative to docker-compose.yml location
    hostname: sub-service
    ports:
      - 5052:5052  # host:container
    networks:
      sample:
        aliases:
          - sub-service
  # Add more services below
  mul-service:
    build: ./mul-service # path is relative to docker-compose.yml location
    hostname: mul-service
    ports:
      - 5053:5053  # host:container
    networks:
      sample:
        aliases:
          - mul-service
  # Add more services below
  div-service:
    build: ./div-service  # path is relative to docker-compose.yml location
    hostname: div-service
    ports:
      - 5054:5054  # host:container
    networks:
      sample:
        aliases:
          - div-service
networks:
  sample: